apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
  - redis.yaml
  - php-migration-job.yaml
  - php-deployment.yaml
  - php-service.yaml
  - php-ingress.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-ingress.yaml
  - keycloak-configmap.yaml
  - keycloak-deployment.yaml
  - keycloak-service.yaml
  - keycloak-ingress.yaml
