apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hostium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/apperturedev/podium.git
    targetRevision: HEAD
    path: deploy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: hostium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
